// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618063209_AddTicketsAndSupportReplyTables")]
    partial class AddTicketsAndSupportReplyTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.Entities.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttractionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("ClosedAt")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Entry_Fee");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<TimeOnly?>("OpenAt")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("Domain.Entities.AttractionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttractionId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.ToTable("AttractionCategories");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BookingNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(20)")
                        .HasComputedColumnSql("CONVERT(varchar(8), [BookingDate], 112) + RIGHT('000000' + CAST([Id] AS varchar(6)), 6)", true);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DietaryRequirements")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FlightCabinClass")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfAdults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("NumberOfChildren")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RoomTypePreference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("TourPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Booking_BookingStatus", "[Status] IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)");

                            t.HasCheckConstraint("CK_Booking_FlightCabinClass", "[FlightCabinClass] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Amman",
                            CountryId = 1,
                            Description = "The capital of Jordan.",
                            Latitude = 31.945400m,
                            Longitude = 35.928400m
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Aqaba",
                            CountryId = 1,
                            Description = "Red Sea coastal city and diving hub.",
                            Latitude = 29.526700m,
                            Longitude = 35.007800m
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Petra",
                            CountryId = 1,
                            Description = "Ancient rose-red city, a wonder of the world.",
                            Latitude = 30.328500m,
                            Longitude = 35.444400m
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Irbid",
                            CountryId = 1,
                            Description = "Northern university city.",
                            Latitude = 32.555600m,
                            Longitude = 35.850000m
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Damascus",
                            CountryId = 2,
                            Description = "One of the oldest continuously inhabited cities.",
                            Latitude = 33.513800m,
                            Longitude = 36.276500m
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Aleppo",
                            CountryId = 2,
                            Description = "Historic city famous for its citadel and souks.",
                            Latitude = 36.202100m,
                            Longitude = 37.134300m
                        },
                        new
                        {
                            Id = 7,
                            CityName = "Homs",
                            CountryId = 2,
                            Description = "Central Syrian city.",
                            Latitude = 34.732400m,
                            Longitude = 36.713700m
                        },
                        new
                        {
                            Id = 8,
                            CityName = "Latakia",
                            CountryId = 2,
                            Description = "Main Mediterranean port city.",
                            Latitude = 35.519600m,
                            Longitude = 35.791500m
                        },
                        new
                        {
                            Id = 9,
                            CityName = "Beirut",
                            CountryId = 3,
                            Description = "The capital and cultural heart of Lebanon.",
                            Latitude = 33.893800m,
                            Longitude = 35.501800m
                        },
                        new
                        {
                            Id = 10,
                            CityName = "Tripoli",
                            CountryId = 3,
                            Description = "Northern city rich in Mamluk architecture.",
                            Latitude = 34.436700m,
                            Longitude = 35.849700m
                        },
                        new
                        {
                            Id = 11,
                            CityName = "Byblos",
                            CountryId = 3,
                            Description = "Ancient port, among the oldest cities in the world.",
                            Latitude = 34.123200m,
                            Longitude = 35.651000m
                        },
                        new
                        {
                            Id = 12,
                            CityName = "Cairo",
                            CountryId = 4,
                            Description = "The capital, home to the Giza pyramids nearby.",
                            Latitude = 30.044400m,
                            Longitude = 31.235700m
                        },
                        new
                        {
                            Id = 13,
                            CityName = "Alexandria",
                            CountryId = 4,
                            Description = "Mediterranean port city founded by Alexander the Great.",
                            Latitude = 31.200100m,
                            Longitude = 29.918700m
                        },
                        new
                        {
                            Id = 14,
                            CityName = "Luxor",
                            CountryId = 4,
                            Description = "Open-air museum of ancient Egyptian temples.",
                            Latitude = 25.687200m,
                            Longitude = 32.639600m
                        },
                        new
                        {
                            Id = 15,
                            CityName = "Sharm El Sheikh",
                            CountryId = 4,
                            Description = "Red Sea resort town.",
                            Latitude = 27.915800m,
                            Longitude = 34.330000m
                        },
                        new
                        {
                            Id = 16,
                            CityName = "Dubai",
                            CountryId = 5,
                            Description = "Global city known for skyscrapers and shopping.",
                            Latitude = 25.204800m,
                            Longitude = 55.270800m
                        },
                        new
                        {
                            Id = 17,
                            CityName = "Abu Dhabi",
                            CountryId = 5,
                            Description = "The capital of the UAE.",
                            Latitude = 24.453900m,
                            Longitude = 54.377300m
                        },
                        new
                        {
                            Id = 18,
                            CityName = "Sharjah",
                            CountryId = 5,
                            Description = "Cultural capital of the UAE.",
                            Latitude = 25.346300m,
                            Longitude = 55.420900m
                        },
                        new
                        {
                            Id = 19,
                            CityName = "Istanbul",
                            CountryId = 6,
                            Description = "Transcontinental city spanning Europe and Asia.",
                            Latitude = 41.008200m,
                            Longitude = 28.978400m
                        },
                        new
                        {
                            Id = 20,
                            CityName = "Ankara",
                            CountryId = 6,
                            Description = "The capital of Turkey.",
                            Latitude = 39.933400m,
                            Longitude = 32.859700m
                        },
                        new
                        {
                            Id = 21,
                            CityName = "Antalya",
                            CountryId = 6,
                            Description = "Mediterranean resort city on the Turkish Riviera.",
                            Latitude = 36.896900m,
                            Longitude = 30.713300m
                        },
                        new
                        {
                            Id = 22,
                            CityName = "Cappadocia",
                            CountryId = 6,
                            Description = "Famous for fairy chimneys and hot-air balloons.",
                            Latitude = 38.643100m,
                            Longitude = 34.828900m
                        },
                        new
                        {
                            Id = 23,
                            CityName = "Riyadh",
                            CountryId = 7,
                            Description = "The capital of Saudi Arabia.",
                            Latitude = 24.713600m,
                            Longitude = 46.675300m
                        },
                        new
                        {
                            Id = 24,
                            CityName = "Jeddah",
                            CountryId = 7,
                            Description = "Red Sea port city and gateway to Mecca.",
                            Latitude = 21.485800m,
                            Longitude = 39.192500m
                        },
                        new
                        {
                            Id = 25,
                            CityName = "Mecca",
                            CountryId = 7,
                            Description = "The holiest city in Islam.",
                            Latitude = 21.389100m,
                            Longitude = 39.857900m
                        },
                        new
                        {
                            Id = 26,
                            CityName = "Medina",
                            CountryId = 7,
                            Description = "The second holiest city in Islam.",
                            Latitude = 24.524700m,
                            Longitude = 39.569200m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Companion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NationalityCountryId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.Property<string>("ResidencyCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalityCountryId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Companions", t =>
                        {
                            t.HasCheckConstraint("CHK_Companion_Relationship", "[Relationship] IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Companion_Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("CompanionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CompanionId");

                    b.ToTable("CompanionBookings");
                });

            modelBuilder.Entity("Domain.Entities.Company_TouristGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TouristGuideId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("TouristGuideId");

                    b.HasIndex("CompanyId", "TouristGuideId")
                        .IsUnique();

                    b.ToTable("CompanyGuides", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Flag")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "JO",
                            CountryName = "Jordan",
                            Latitude = 31.945400m,
                            Longitude = 35.928400m
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "SY",
                            CountryName = "Syria",
                            Latitude = 33.513800m,
                            Longitude = 36.276500m
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "LB",
                            CountryName = "Lebanon",
                            Latitude = 33.893800m,
                            Longitude = 35.501800m
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "EG",
                            CountryName = "Egypt",
                            Latitude = 30.044400m,
                            Longitude = 31.235700m
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "AE",
                            CountryName = "United Arab Emirates",
                            Latitude = 24.453900m,
                            Longitude = 54.377300m
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "TR",
                            CountryName = "Turkey",
                            Latitude = 39.933400m,
                            Longitude = 32.859700m
                        },
                        new
                        {
                            Id = 7,
                            CountryCode = "SA",
                            CountryName = "Saudi Arabia",
                            Latitude = 24.713600m,
                            Longitude = 46.675300m
                        });
                });

            modelBuilder.Entity("Domain.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("Domain.Entities.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("EmailVerification");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EmailVer__3214EC075FAC316A");

                    b.HasIndex(new[] { "UserId" }, "IX_EmailVerifications_UserId");

                    b.HasIndex(new[] { "UserId", "IsUsed" }, "IX_EmailVerifications_UserId_IsUsed");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Domain.Entities.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DayDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("DayTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CHK_PaymentStatuses", "[PaymentStatus] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalIdCard")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NationalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassportScan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ResidentialCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("ResidentialCityId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Domain.Entities.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("RateValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entities.SupportReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReplyContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("SupportReplies");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.TourCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateOnly?>("FoundingDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TourismLicenseImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TourismLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TourCompanies");
                });

            modelBuilder.Entity("Domain.Entities.TourPackage_Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttractionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("PackageId", "AttractionId")
                        .IsUnique();

                    b.ToTable("PackageAttractions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TourPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("BusinessClassPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<decimal>("EconomyClassPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MeetingPoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PremiumClassPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PublishCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("RegistrationDeadline")
                        .HasColumnType("date");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ServiceLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.ToTable("TourPackages");
                });

            modelBuilder.Entity("Domain.Entities.TourPackageCabinClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinClass")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "CabinClass")
                        .IsUnique();

                    b.ToTable("TourPackageCabinClasses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TourPackageMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TourPackageId");

                    b.ToTable("TourPackageMedias");
                });

            modelBuilder.Entity("Domain.Entities.TourPackage_TouristGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("TouristGuideId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("TouristGuideId");

                    b.HasIndex("PackageId", "TouristGuideId")
                        .IsUnique();

                    b.ToTable("TourPackageGuides", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TouristGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Languages")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LicenseScan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NationalityCountryId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperiance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalityCountryId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("TouristGuides", t =>
                        {
                            t.HasCheckConstraint("CHK_Positive_YearsOfExperience", "[YearsOfExperiance] BETWEEN 0 AND 70");
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccount")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Domain.Entities.Activity", b =>
                {
                    b.HasOne("Domain.Entities.Itinerary", "Itinerary")
                        .WithMany("Activities")
                        .HasForeignKey("ItineraryId")
                        .IsRequired()
                        .HasConstraintName("FK__PackageIt__Itine__2645B050");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Domain.Entities.Attraction", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Attractio__CityI__6EF57B66");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.AttractionCategory", b =>
                {
                    b.HasOne("Domain.Entities.Attraction", "Attraction")
                        .WithMany("AttractionCategories")
                        .HasForeignKey("AttractionId")
                        .IsRequired()
                        .HasConstraintName("FK__Attractio__Attra__73BA3083");

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.HasOne("Domain.Entities.Payment", "Payment")
                        .WithOne("Booking")
                        .HasForeignKey("Domain.Entities.Booking", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_payments");

                    b.HasOne("Domain.Entities.TourPackage", "TourPackage")
                        .WithMany("Bookings")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__UserId__0F624AF8");

                    b.Navigation("Payment");

                    b.Navigation("TourPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__CountryI__60A75C0F");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Companion", b =>
                {
                    b.HasOne("Domain.Entities.Country", "NationalityCountry")
                        .WithMany("NatinalityCompanions")
                        .HasForeignKey("NationalityCountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithOne("Companion")
                        .HasForeignKey("Domain.Entities.Companion", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Companions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NationalityCountry");

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Companion_Booking", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("CompanionBookings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Companion", "Companion")
                        .WithMany("CompanionBookings")
                        .HasForeignKey("CompanionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Companion");
                });

            modelBuilder.Entity("Domain.Entities.Company_TouristGuide", b =>
                {
                    b.HasOne("Domain.Entities.TourCompany", "Company")
                        .WithMany("CompanyGuides")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyGuides_TourCompanies");

                    b.HasOne("Domain.Entities.TouristGuide", "TouristGuide")
                        .WithMany("CompanyGuides")
                        .HasForeignKey("TouristGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyGuides_TouristGuides");

                    b.Navigation("Company");

                    b.Navigation("TouristGuide");
                });

            modelBuilder.Entity("Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.EmailVerification", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmailVerifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Favorite", b =>
                {
                    b.HasOne("Domain.Entities.TourCompany", "Company")
                        .WithMany("Favorites")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__Compa__3A4CA8FD");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__UserI__3B40CD36");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Itinerary", b =>
                {
                    b.HasOne("Domain.Entities.TourPackage", "Package")
                        .WithMany("PackageItineraries")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK__PackageIt__Packa__6A30C649");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Notificat__Booki__17F790F9");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__17036CC0");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__payments__UserId__756D6ECB");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.HasOne("Domain.Entities.City", "ResidentialCity")
                        .WithMany("Persons")
                        .HasForeignKey("ResidentialCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResidentialCity");
                });

            modelBuilder.Entity("Domain.Entities.Rate", b =>
                {
                    b.HasOne("Domain.Entities.TourPackage", "Package")
                        .WithMany("Rates")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK__Rates__PackageId__3587F3E0");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Rates")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Rates__UserId__3493CFA7");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.HasOne("Domain.Entities.TourPackage", "Package")
                        .WithMany("Reviews")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__Package__1EA48E88");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__UserId__1CBC4616");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SupportReply", b =>
                {
                    b.HasOne("Domain.Entities.User", "Admin")
                        .WithMany("SupportReplies")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SupportReplies_Admins");

                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithOne("SupportReply")
                        .HasForeignKey("Domain.Entities.SupportReply", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SupportReplies_Tickets");

                    b.Navigation("Admin");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.TourCompany", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("TourCompany")
                        .HasForeignKey("Domain.Entities.TourCompany", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TourCompa__UserI__5812160E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.TourPackage_Attraction", b =>
                {
                    b.HasOne("Domain.Entities.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .IsRequired()
                        .HasConstraintName("FK_PackageCities_Attractions");

                    b.HasOne("Domain.Entities.TourPackage", "Package")
                        .WithMany("PackageAttractions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PackageCities_TourPackages");

                    b.Navigation("Attraction");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Domain.Entities.TourPackage", b =>
                {
                    b.HasOne("Domain.Entities.TourCompany", "Company")
                        .WithMany("TourPackages")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK__TourPacka__Compa__656C112C");

                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("TourPackages")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_TourPackages_Countries");

                    b.Navigation("Company");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.TourPackageCabinClass", b =>
                {
                    b.HasOne("Domain.Entities.TourPackage", "Package")
                        .WithMany("CabinClasses")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TourPackageCabinClasses_TourPackages");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Domain.Entities.TourPackageMedia", b =>
                {
                    b.HasOne("Domain.Entities.TourPackage", "TourPackage")
                        .WithMany("Media")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TourPackageMedia_TourPackages");

                    b.Navigation("TourPackage");
                });

            modelBuilder.Entity("Domain.Entities.TourPackage_TouristGuide", b =>
                {
                    b.HasOne("Domain.Entities.TourPackage", "Package")
                        .WithMany("TourPackageGuides")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TourPackageGuides_TourPackages");

                    b.HasOne("Domain.Entities.TouristGuide", "TouristGuide")
                        .WithMany("TourPackageGuides")
                        .HasForeignKey("TouristGuideId")
                        .IsRequired()
                        .HasConstraintName("FK_TourPackageGuides_TouristGuides");

                    b.Navigation("Package");

                    b.Navigation("TouristGuide");
                });

            modelBuilder.Entity("Domain.Entities.TouristGuide", b =>
                {
                    b.HasOne("Domain.Entities.Country", "NatinalityCountry")
                        .WithMany()
                        .HasForeignKey("NationalityCountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithOne("TouristGuide")
                        .HasForeignKey("Domain.Entities.TouristGuide", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NatinalityCountry");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Domain.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__4F7CD00D");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Wishlist", b =>
                {
                    b.HasOne("Domain.Entities.TourPackage", "TourPackage")
                        .WithMany("Wishlists")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__Wishlists__Attra__2FCF1A8A");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Wishlists__UserI__2EDAF651");

                    b.Navigation("TourPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Attraction", b =>
                {
                    b.Navigation("AttractionCategories");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Navigation("CompanionBookings");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Domain.Entities.Companion", b =>
                {
                    b.Navigation("CompanionBookings");
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("NatinalityCompanions");

                    b.Navigation("TourPackages");
                });

            modelBuilder.Entity("Domain.Entities.Itinerary", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Navigation("Booking")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Navigation("Companion")
                        .IsRequired();

                    b.Navigation("TouristGuide")
                        .IsRequired();

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Navigation("SupportReply");
                });

            modelBuilder.Entity("Domain.Entities.TourCompany", b =>
                {
                    b.Navigation("CompanyGuides");

                    b.Navigation("Favorites");

                    b.Navigation("TourPackages");
                });

            modelBuilder.Entity("Domain.Entities.TourPackage", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CabinClasses");

                    b.Navigation("Media");

                    b.Navigation("PackageAttractions");

                    b.Navigation("PackageItineraries");

                    b.Navigation("Rates");

                    b.Navigation("Reviews");

                    b.Navigation("TourPackageGuides");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Domain.Entities.TouristGuide", b =>
                {
                    b.Navigation("CompanyGuides");

                    b.Navigation("TourPackageGuides");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Companions");

                    b.Navigation("EmailVerifications");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Rates");

                    b.Navigation("Reviews");

                    b.Navigation("SupportReplies");

                    b.Navigation("Tickets");

                    b.Navigation("TourCompany");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
